// Execute the active note-centric browser controller with synthetic data.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(process.argv[2],'utf8');
function harness(){
 const nodes=new Map();class Element{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.value='';}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(x){this.children.push(x);}replaceChildren(){for(const key of [...nodes.keys()])if(key.startsWith('edit-')||key==='research-note'||key==='save-resolution')nodes.delete(key);this.children=[];}setAttribute(){}focus(){}}
 for(const id of ['queue','session','start','progress','message','context','coverage','audits','start-review','reviewer','refresh','preview','patch','status-filter','export-path','export-generate','export-preview','export-summary']){const e=new Element('div');e.id=id;}
 const note={id:1,fields:[{name:'Text',value:'old text'},{name:'Extra',value:'old extra'}]},base={specialty:'test',subspecialty:'test',confidence:'high',severity:'moderate',category:'oversimplification',audit_version:'v2',audit_date:'today',evidence:[],history:[],note};
 const findings=[{...base,id:'text',guid:'g1',field:'Text',rationale:'text concern',evidence_status:'editorial',original:'old text',replacement:'new text',review:{id:0,status:'awaiting_review',final:null,edits:[]}},{...base,id:'extra',guid:'g1',field:'Extra',rationale:'extra concern',evidence_status:'needs_research',original:'old extra',replacement:null,review:{id:7,status:'needs_research',reviewer:'Chris',comment:'',created:'today',final:null,edits:[]}}];
 const initial={findings,batch:{id:'abcdef',version:'test'},coverage:{},audits:[],suggested_export_path:'/Users/chrishornung/Developer/Anki/2026-09-30ApprovedExport.apkg'};let pending,calls=[],confirmCalls=0,keydown,stored={};
 const ctx=vm.createContext({document:{getElementById:id=>nodes.get(id),createElement:tag=>new Element(tag),addEventListener:(name,fn)=>{if(name==='keydown')keydown=fn;}},window:{addEventListener(){},confirm:()=>{confirmCalls++;return true;}},localStorage:{getItem:k=>stored[k]||'',setItem:(k,v)=>stored[k]=v},fetch:async(path,opts)=>{if(!opts.body)return{ok:true,json:async()=>initial};calls.push(JSON.parse(opts.body));return new Promise(resolve=>pending=resolve);}});
 vm.runInContext(source,ctx);return{nodes,calls,ctx,findings,settle:()=>new Promise(r=>setImmediate(r)),run:s=>vm.runInContext(s,ctx),reply(){const body=calls.at(-1),f=findings.find(x=>x.id===body.id),review={...body,id:99,created:'saved',edits:body.edits||[]};pending({ok:true,json:async()=>({saved:true,finding:{...f,review,history:[review]}})});},confirmCalls:()=>confirmCalls,stored,key:k=>keydown({key:k,repeat:false,ctrlKey:false,metaKey:false,altKey:false,target:{tagName:'DIV',isContentEditable:false},preventDefault(){}})};
}
const rendered=h=>h.run("(function walk(x){return [x.textContent||'',...x.children.flatMap(walk)]})(document.getElementById('queue'))");
(async()=>{
 const h=harness();await h.settle();assert.equal(h.nodes.get('export-path').value,'/Users/chrishornung/Developer/Anki/2026-09-30ApprovedExport.apkg');h.nodes.get('reviewer').value='Chris';h.run('startReview()');let view=rendered(h);assert(view.includes('Text · finding/proposal')&&view.includes('Extra · finding/proposal'));assert(view.includes('old text')&&view.includes('old extra'));assert.equal(h.run('notes().length'),1);
 h.run("setFilter('needs_research')");assert.equal(h.stored['crabs-review-filter'],'needs_research');assert.equal(h.run('notes()[0].findings[1].review.status'),'needs_research');view=rendered(h);assert(view.includes('Reopen / change decision'));
 h.run("editProposal(data.findings[1])");h.nodes.get('edit-Extra').value='researched extra';h.nodes.get('research-note').value='Checked guideline section 4';const saving=h.run("decideFinding(data.findings[1],'approved',true)");assert.deepEqual(h.calls[0].edits.map(e=>[e.field,e.final]),[['Extra','researched extra']]);assert.equal(h.calls[0].comment,'Checked guideline section 4');h.reply();await saving;assert.equal(h.run('dirty()'),false);assert.equal(h.confirmCalls(),0);
 h.run("setFilter('all');editProposal(data.findings[0])");h.nodes.get('edit-Text').value='new text';h.nodes.get('edit-Extra').value='qualified extra';const both=h.run("decideFinding(data.findings[0],'approved',true)");assert.deepEqual(h.calls[1].edits.map(e=>[e.field,e.final]),[['Text','new text'],['Extra','qualified extra']]);h.reply();await both;assert.equal(h.run('dirty()'),false);assert.equal(h.run("data.findings[0].review.status"),'approved');
 assert.equal(JSON.stringify(h.run("comparison('old value','new value')")),JSON.stringify([['insert','','new'],['delete','old',''],['equal',' value',' value']]));
 console.log('PASS: note grouping; Text/Extra context; needs-research queue; reopen; cross-field edit; durable baseline; diff');
})().catch(e=>{console.error(e);process.exitCode=1;});
