// Execute the actual browser controller with a minimal DOM and controlled HTTP promises.
const assert=require('node:assert/strict'), fs=require('node:fs'), vm=require('node:vm');
const source=fs.readFileSync(process.argv[2],'utf8');
function harness(state){
 const nodes=new Map();
 class Element {constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.value='';}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(x){this.children.push(x);}replaceChildren(){nodes.delete('edit');this.children=[];}setAttribute(){}focus(){}}
 for(const id of ['queue','session','start','progress','message','context','coverage','audits','start-review','reviewer','refresh','preview','patch']){const e=new Element('div');e.id=id;}
 const findings=Array.from({length:3},(_,i)=>({id:String(i),guid:`g${i}`,field:'Text',specialty:'test',subspecialty:'test',confidence:'high',severity:'low',category:'ambiguous_wording',rationale:'test',evidence_status:'editorial',audit_version:'test',audit_date:'today',review:{id:0,status:'awaiting_review',final:null,edits:[]},original:'old',replacement:'new',diff:[['replace','old','new']],evidence:[],history:[],note:{id:i,fields:[{name:'Text',value:'old'},{name:'Extra',value:'context'}]}}));
 let pending, calls=[];let confirm=true,confirmCalls=0,keydown;
 const initial=state||{findings,batch:{id:'abcdef',version:'test'},coverage:{},audits:[]};
 const ctx=vm.createContext({document:{getElementById:id=>nodes.get(id),createElement:tag=>new Element(tag),addEventListener:(name,fn)=>{if(name==='keydown')keydown=fn;}},window:{addEventListener(){},confirm:()=>{confirmCalls++;return confirm;}},localStorage:{getItem:()=>'',setItem(){}},fetch:async(path,opts)=>{if(!opts.body)return {ok:true,json:async()=>initial};calls.push(JSON.parse(opts.body));return new Promise(resolve=>pending=resolve);}});
 vm.runInContext(source,ctx);return {nodes,calls,run:s=>vm.runInContext(s,ctx),confirmCalls:()=>confirmCalls,key(value){keydown({key:value,repeat:false,ctrlKey:false,metaKey:false,altKey:false,target:{tagName:'DIV',isContentEditable:false},preventDefault(){}});},settle:async()=>{await new Promise(r=>setImmediate(r));},reply(ok=true){const body=calls.at(-1),own=(body.edits||[]).find(e=>e.field==='Text'),review={...body,final:own?own.final:body.final,id:42,created:'today',edits:body.edits||[]};pending({ok,json:async()=>ok?{saved:true,finding:body.id===undefined?undefined:{...findings[Number(body.id)],review,history:[{...review,finding_id:body.id}]}}:{error:'disk failure'}});},deny(){confirm=false;}};
}
(async()=>{
 for(const status of ['approved','rejected','deferred']){
  const h=harness();await h.settle();await h.run(`decideFinding('${status}')`);assert.equal(h.calls.length,0);assert.equal(h.nodes.get('queue').children.length,0);
  h.nodes.get('reviewer').value='   ';h.run('startReview()');assert.equal(h.run('reviewer'),'');
  h.nodes.get('reviewer').value=' Chris Hornung ';h.run('startReview()');
  const saving=h.run(`decideFinding('${status}')`);assert.equal(h.run('index'),0);assert.equal(h.run('busy'),true,h.nodes.get('message').textContent);assert.equal(h.calls[0].reviewer,'Chris Hornung');
  await h.run(`decideFinding('${status}')`);assert.equal(h.calls.length,1);h.reply();await saving;
  assert.equal(h.run('index'),1);assert.match(h.nodes.get('message').textContent,/Chris Hornung · saved/);h.run('navigate(0)');assert.equal(h.run('data.findings[0].review.status'),status);
 }
 const h=harness();await h.settle();h.nodes.get('reviewer').value='Chris';h.run('startReview();editProposal()');h.nodes.get('edit').value='edited';h.deny();h.run('navigate(1)');assert.equal(h.run('index'),0);
 const saving=h.run("decideFinding('approved',true)");h.reply(false);await saving;assert.equal(h.run('index'),0);assert.equal(h.nodes.get('edit').value,'edited');assert.equal(h.run('dirty()'),true);
 const retry=h.run("decideFinding('approved',true)");assert.deepEqual(h.calls.at(-1).edits.map(x=>[x.field,x.final]),[['Text','edited']]);h.reply();await retry;assert.equal(h.run('data.findings[0].replacement'),'new');assert.equal(h.run('data.findings[0].review.final'),'edited');
 h.run('navigate(2)');assert.equal(h.calls.length,2);assert.equal(h.run('data.findings[2].review.id'),0);
 for(const status of ['rejected','deferred']){const save=h.run(`decideFinding('${status}')`);h.reply();await save;}
 assert.equal(h.run('complete'),true);assert.match(h.nodes.get('progress').textContent,/3 \/ 3 field units resolved/);
 const keys=harness();await keys.settle();keys.nodes.get('reviewer').value='Chris';keys.run('startReview()');keys.key('a');assert.equal(keys.calls[0].status,'approved');keys.reply();await keys.settle();
 const unchanged={findings:[],batch:{id:'abcdef',version:'test'},coverage:{},audits:[],queue:[{kind:'unchanged',guid:'g',field:'Extra',resolved:false,review:{id:0,status:'awaiting_review'},note:{id:1,fields:[{name:'Extra',value:'ok'}]},note_status:{status:'unreviewed',fields:[{name:'Extra',status:'pending',finding_count:0}]}}]};
 const uk=harness(unchanged);await uk.settle();uk.nodes.get('reviewer').value='Chris';uk.run('startReview()');uk.key('u');assert.equal(uk.calls[0].status,'reviewed_unchanged');uk.reply();await uk.settle();
 const switcher=harness();await switcher.settle();switcher.nodes.get('reviewer').value='Chris';switcher.run('startReview();editProposal()');switcher.nodes.get('edit').value='text draft';switcher.run("selectField('Extra')");switcher.nodes.get('edit').value='extra draft';switcher.run("selectField('Text')");assert.equal(switcher.nodes.get('edit').value,'text draft');switcher.run("selectField('Extra')");assert.equal(switcher.nodes.get('edit').value,'extra draft');const both=switcher.run("decideFinding('approved',true)");assert.deepEqual(switcher.calls[0].edits.map(x=>[x.field,x.final]),[['Text','text draft'],['Extra','extra draft']]);switcher.reply();await both;
 const cross=harness();await cross.settle();cross.nodes.get('reviewer').value='Chris';cross.run("startReview();editProposal()");cross.nodes.get('edit').value='old';cross.run("selectField('Extra')");cross.nodes.get('edit').value='qualified context';const crossSave=cross.run("decideFinding('approved',true)");assert.deepEqual(cross.calls[0].edits.map(x=>[x.field,x.final]),[['Extra','qualified context']]);cross.reply();await crossSave;
 const seeded=harness();await seeded.settle();seeded.nodes.get('reviewer').value='Chris';seeded.run('startReview();editProposal()');assert.equal(seeded.nodes.get('edit').value,'new');
 assert.equal(JSON.stringify(seeded.run("comparison('old value','new value')")),JSON.stringify([['insert','','new'],['delete','old',''],['equal',' value',' value']]));
 const binding=harness();await binding.settle();binding.nodes.get('reviewer').value='Chris';binding.run("startReview();selectField('Extra')");const rendered=binding.run("(function walk(x){return [x.textContent||'',...x.children.flatMap(walk)]})(document.getElementById('queue'))");assert(rendered.includes('Extra current/original value (exact)'));assert(rendered.includes('context'));assert(!rendered.includes('Text current/original value (exact)'));
 const researchState=harness();await researchState.settle();researchState.run("data.findings[0].evidence_status='needs_research';data.findings[0].replacement=null;render()");researchState.nodes.get('reviewer').value='Chris';researchState.run('startReview();editProposal()');researchState.nodes.get('edit').value='researched correction';researchState.nodes.get('research-note').value='guideline section 4';const researched=researchState.run("decideFinding('approved',true)");assert.equal(researchState.calls[0].comment,'guideline section 4');researchState.reply();await researched;
 const persisted=harness();await persisted.settle();persisted.nodes.get('reviewer').value='Chris';persisted.run('startReview();editProposal()');persisted.nodes.get('edit').value='old';persisted.run("selectField('Extra')");persisted.nodes.get('edit').value='persisted extra';const persistedSave=persisted.run("decideFinding('approved',true)");persisted.reply();await persistedSave;assert.equal(persisted.run('dirty()'),false);const afterSaveIndex=persisted.run('index');persisted.run(`navigate(${Math.min(2,afterSaveIndex+1)})`);assert.equal(persisted.confirmCalls(),0);persisted.run('navigate(0)');persisted.run("selectField('Extra')");const persistedView=persisted.run("(function walk(x){return [x.textContent||'',...x.children.flatMap(walk)]})(document.getElementById('queue'))");assert(persistedView.includes('Approved final / added'));assert(persistedView.includes('persisted extra'));assert.equal(persisted.run("data.findings[0].review.edits[0].field"),'Extra');persisted.run('editProposal()');assert.equal(persisted.nodes.get('edit').value,'persisted extra');assert.equal(persisted.run('dirty()'),false);
 console.log('PASS: field switching/drafts; proposal seeding; colored diff state; research correction; identity gate; shortcuts; durable navigation');
})().catch(e=>{console.error(e);process.exitCode=1;});
