// Field-aware local review session. Position advances only after a durable save.
let data, reviewer='', index=0, busy=false, editing=false, fieldDrafts={}, researchNote='', viewField=null, editFindingId=null, complete=false;
const el=id=>document.getElementById(id);
const text=(tag,value,parent)=>{const x=document.createElement(tag);x.textContent=value;parent.append(x);return x;};
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-CRABS-Review':'1'},body:JSON.stringify(body)}:{});const x=await r.json();if(!r.ok)throw Error(x.error||'Could not save decision');return x;}
function message(value,error=false){el('message').textContent=value;el('message').className=error?'error':'';}
function saveVisibleDraft(){if(editing&&viewField&&el('edit'))fieldDrafts[viewField]=el('edit').value;if(editing&&el('research-note'))researchNote=el('research-note').value;}
function baselineFields(u){const values=Object.fromEntries(u.note.fields.map(x=>[x.name,x.value])),f=u.finding;if(f&&f.review.status==='approved')for(const edit of f.review.edits||[])values[edit.field]=edit.final;return values;}
function dirty(){if(!editing)return false;saveVisibleDraft();const baseline=baselineFields(units()[index]);return Object.keys(baseline).some(name=>fieldDrafts[name]!==baseline[name]);}
function changedEdits(u){const baseline=baselineFields(u);return u.note.fields.filter(x=>fieldDrafts[x.name]!==baseline[x.name]).map(x=>({field:x.name,original:x.value,final:fieldDrafts[x.name]}));}
function canLeave(){return !busy&&(!dirty()||window.confirm('Discard unsaved edits?'));}
function label(f){return f.review.status==='approved'?(f.review.final!==f.replacement?'Edited + approved':'Approved'):({rejected:'Rejected',deferred:'Deferred',needs_research:'Needs research',awaiting_review:'Awaiting review'}[f.review.status]);}
function button(label,action,parent,disabled=false){const b=text('button',label,parent);b.disabled=disabled;b.onclick=action;return b;}
function diff(parent,parts,side){const p=text('pre','',parent);for(const part of parts)if(part[side])text(part[0]==='equal'?'span':side===1?'del':'ins',part[side],p);}
function comparison(oldValue,newValue){
 const old=(oldValue||'').match(/\s+|[\p{L}\p{N}_]+|[^\p{L}\p{N}_\s]/gu)||[],next=(newValue||'').match(/\s+|[\p{L}\p{N}_]+|[^\p{L}\p{N}_\s]/gu)||[],rows=old.length+1,cols=next.length+1,dp=Array.from({length:rows},()=>Array(cols).fill(0));
 for(let i=old.length-1;i>=0;i--)for(let j=next.length-1;j>=0;j--)dp[i][j]=old[i]===next[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);
 const parts=[];let i=0,j=0;const push=(tag,a,b)=>{const last=parts.at(-1);if(last&&last[0]===tag){last[1]+=a;last[2]+=b;}else parts.push([tag,a,b]);};
 while(i<old.length||j<next.length){if(i<old.length&&j<next.length&&old[i]===next[j]){push('equal',old[i++],next[j++]);}else if(j<next.length&&(i===old.length||dp[i][j+1]>=dp[i+1][j]))push('insert','',next[j++]);else push('delete',old[i++],'');}return parts;
}
function renderDiff(parent,original,final,label){const parts=comparison(original,final),wrap=text('div','',parent);wrap.className='diff-grid';const before=text('section','',wrap),after=text('section','',wrap);text('h4','Current / removed',before);diff(before,parts,1);text('h4',label||'Proposed / added',after);diff(after,parts,2);}
function units(){return data.queue||data.findings.map(f=>({kind:'finding',guid:f.guid,field:f.field,resolved:!!f.review.id,finding:f,note:f.note,note_status:{status:'unreviewed',fields:[]}}));}
function unresolved(u){return !u.resolved;}
function syncNote(guid){const q=units(),related=q.filter(u=>u.guid===guid),template=related[0]&&related[0].note_status;if(!template)return;const fields=template.fields.map(f=>{const fieldUnits=related.filter(u=>u.field===f.name);return {...f,status:fieldUnits.length&&fieldUnits.every(u=>u.resolved)?'resolved':'pending'};});const count=fields.filter(f=>f.status==='resolved').length,status=count===0?'unreviewed':count===fields.length?'complete':'partially_reviewed';for(const u of related)u.note_status={...u.note_status,fields,status};}
function clearEditor(){editing=false;fieldDrafts={};researchNote='';viewField=null;editFindingId=null;}
function navigate(next){if(!canLeave())return;clearEditor();complete=false;index=next;render();}
function selectField(name){saveVisibleDraft();viewField=name;render();if(editing&&el('edit'))el('edit').focus();}
function fieldSummary(a,u){const box=text('p','Fields: ',a),fields=(u.note_status&&u.note_status.fields)||[],selected=u.kind==='finding'?(viewField||u.field):u.field;for(const f of fields){if(u.kind==='finding'){const b=button(`${f.name} [${f.status}]`,()=>selectField(f.name),box,busy);if(f.name===selected)b.className='field-current';}else text('span',`${f.name} [${f.status}]  `,box);}text('p',`Note status: ${(u.note_status&&u.note_status.status)||'unreviewed'} · Finding field: ${u.field} · Displayed field: ${selected}`,a);}
function render(){
 el('queue').replaceChildren();el('session').hidden=!reviewer;el('start').hidden=!!reviewer;if(!data)return;
 const q=units(),resolved=q.filter(x=>x.resolved).length;el('progress').textContent=`${resolved} / ${q.length} field units resolved · ${reviewer}`;if(!reviewer)return;
 if(complete||!q.length){text('h2','Review complete',el('queue'));text('p',`Resolved field units: ${resolved}`,el('queue'));if(q.length)button('Revisit fields',()=>navigate(0),el('queue'));return;}
 const u=q[index],a=text('article','',el('queue'));fieldSummary(a,u);
 if(u.kind==='unchanged'){
  text('h2',`Field ${index+1} / ${q.length} · ${u.field} · no finding`,a);text('p',u.resolved?`Reviewed unchanged · ${u.review.reviewer} · ${u.review.created}`:'Awaiting field review',a);text('p',`GUID ${u.guid} | Note ${u.note.id}`,a);text('h3','Current field (exact)',a);text('pre',u.note.fields.find(x=>x.name===u.field).value,a);button('Reviewed unchanged (U)',decideUnchanged,a,busy||u.resolved||!reviewer.trim());
 }else{
  const f=u.finding;if(editFindingId!==f.id){viewField=f.field;editFindingId=f.id;}const displayed=viewField||f.field,sourceField=u.note.fields.find(x=>x.name===displayed);text('h2',`Finding ${index+1} / ${q.length} · ${f.severity} · ${f.category}`,a);text('p',f.review.status!=='awaiting_review'?`${label(f)} · ${f.review.reviewer} · saved · ${f.review.created}`:'Awaiting review',a);text('p',`GUID ${f.guid} | Finding field: ${f.field} | ${f.specialty} / ${f.subspecialty} | Confidence: ${f.confidence}`,a);text('p',f.rationale,a);text('p',`Evidence: ${f.evidence_status} | ${f.audit_version} | ${f.audit_date}`,a);
  for(const e of f.evidence){const p=text('p',`${e.title} — ${e.organization_authors}, ${e.publication}, ${e.year}. ${e.locator||''} `,a);const link=text('a','Source',p);link.href=e.url;link.target='_blank';link.rel='noreferrer noopener';}
  text('h3',`${displayed} current/original value (exact)`,a);text('pre',sourceField.value,a);
  const proposals=data.findings.filter(x=>x.guid===f.guid&&x.field===displayed&&x.replacement!==null);text('h3',`Existing automated proposal${proposals.length===1?'':'s'} for ${displayed}`,a);if(proposals.length)for(const proposal of proposals)renderDiff(a,sourceField.value,proposal.replacement,'Automated proposal / added');else text('pre','No automated finding or proposal exists for this field. You can still make a human-directed edit.',a);
  text('h3',`${displayed} proposed/final value`,a);
  if(editing){const edit=text('textarea','',a);edit.id='edit';edit.value=fieldDrafts[displayed];edit.setAttribute('aria-label',`Final value for ${displayed}`);edit.disabled=busy;edit.oninput=()=>{fieldDrafts[displayed]=edit.value;const save=el('save-resolution');if(save)save.disabled=busy||!changedEdits(u).length||(f.evidence_status==='needs_research'&&!researchNote.trim());};renderDiff(a,sourceField.value,fieldDrafts[displayed],'Draft final / added');if(proposals.length)button('Reset to automated proposal',()=>{fieldDrafts[displayed]=proposals[0].replacement;render();},a,busy);button('Reset this field to current',()=>{fieldDrafts[displayed]=sourceField.value;render();},a,busy);}else if(f.review.status==='approved'&&f.review.edits&&f.review.edits.some(x=>x.field===displayed)){const saved=f.review.edits.find(x=>x.field===displayed).final;renderDiff(a,sourceField.value,saved,'Approved final / added');}else text('pre',sourceField.value,a);
  const source=text('details','',a);text('summary','Original automated proposal and full source note',source);text('pre',f.replacement??'(No replacement; research required)',source);text('pre',JSON.stringify(u.note,null,2),source);
  const locked=busy||!reviewer.trim(),research=f.evidence_status==='needs_research';if(editing){if(research){const label=text('label','Research / evidence note (required for a human correction)',a),note=text('textarea','',label);note.id='research-note';note.value=researchNote;note.setAttribute('aria-label','Research and evidence note');note.oninput=()=>{researchNote=note.value;const save=el('save-resolution');if(save)save.disabled=busy||!changedEdits(u).length||!researchNote.trim();};}const save=button('Save changed fields & Approve',()=>decideFinding('approved',true),a,locked||!changedEdits(u).length||(research&&!researchNote.trim()));save.id='save-resolution';if(!changedEdits(u).length)text('p','Make a change in at least one field to enable approval.',a);button('Cancel',()=>{if(canLeave()){clearEditor();render();}},a,busy);}else{button('Approve automated proposal (A)',()=>decideFinding('approved'),a,locked||research);button('Reject (R)',()=>decideFinding('rejected'),a,locked);button('Defer (D)',()=>decideFinding('deferred'),a,locked);button('Needs research (N)',()=>decideFinding('needs_research'),a,locked);button('Edit fields + Approve (E)',editProposal,a,locked);}if(research)text('p','Blind approval is blocked. You may defer or mark this finding as needing research, or enter a human correction and document the research/evidence used.',a);const history=text('details','',a);text('summary','Review history',history);text('pre',JSON.stringify(f.history,null,2),history);
 }
 const nav=text('nav','',a);button('Previous',()=>navigate(index-1),nav,busy||index===0);button('Next',()=>navigate(index+1),nav,busy||index===q.length-1);
}
function editProposal(){const u=units()[index],f=u.finding;if(!f||!reviewer.trim()||busy||editing)return;fieldDrafts=baselineFields(u);if(f.review.status!=='approved'&&f.replacement!==null)fieldDrafts[f.field]=f.replacement;researchNote=f.review.status==='approved'?(f.review.comment||''):'';viewField=viewField||f.field;editFindingId=f.id;editing=true;render();el('edit').focus();}
function advance(){const q=units(),current=q[index];const same=q.findIndex((u,i)=>i>index&&!u.resolved&&u.guid===current.guid);const next=same>=0?same:q.findIndex((u,i)=>i>index&&!u.resolved);const first=q.findIndex(unresolved);if(next>=0)index=next;else if(first>=0)index=first;else complete=true;}
async function decideFinding(status,edited=false){if(!reviewer.trim()||busy||(editing&&!edited))return;const u=units()[index],f=u.finding;if(!f||(status==='approved'&&!edited&&f.evidence_status==='needs_research'))return;saveVisibleDraft();const edits=edited?changedEdits(u):undefined;if(edited&&(!edits.length||(f.evidence_status==='needs_research'&&!researchNote.trim())))return;const final=status==='approved'&&!edited?f.replacement:null;busy=true;render();message('Saving…');try{const result=await api('/api/review',{id:f.id,status,reviewer,final,edits,comment:edited?researchNote:'',expected_review_id:f.review.id});if(!result.saved||!result.finding)throw Error('Save was not confirmed. Refresh before retrying.');Object.assign(f,result.finding);u.finding=f;u.resolved=true;syncNote(u.guid);message(`${label(result.finding)} · ${result.finding.review.reviewer} · saved`);clearEditor();advance();}catch(e){message(e.message,true);}finally{busy=false;render();}}
async function decideUnchanged(){if(!reviewer.trim()||busy)return;const u=units()[index];busy=true;render();message('Saving…');try{const result=await api('/api/field-review',{export_id:data.batch.id,guid:u.guid,field:u.field,status:'reviewed_unchanged',reviewer,expected_review_id:u.review.id});if(!result.saved)throw Error('Save was not confirmed.');u.review={id:(u.review.id||0)+1,status:'reviewed_unchanged',reviewer,created:'saved'};u.resolved=true;syncNote(u.guid);message(`Reviewed unchanged · ${reviewer} · saved`);advance();}catch(e){message(e.message,true);}finally{busy=false;render();}}
async function load(){if(!canLeave())return;try{data=await api('/api/state');clearEditor();complete=false;const q=units();index=Math.max(0,q.findIndex(unresolved));el('context').textContent=`Batch: ${data.batch.version} · ${data.batch.id.slice(0,12)} · ${q.length} field units · Audits: ${[...new Set(data.findings.map(f=>f.audit_version))].join(', ')}`;el('coverage').textContent=JSON.stringify({...data.coverage,notes:undefined},null,2);el('audits').textContent=JSON.stringify(data.audits,null,2);el('start-review').disabled=!el('reviewer').value.trim();render();}catch(e){message(e.message,true);}}
function startReview(){if(!data||!el('reviewer').value.trim())return;reviewer=el('reviewer').value.trim();try{localStorage.setItem('crabs-reviewer',reviewer);}catch(e){}index=Math.max(0,units().findIndex(unresolved));render();}
window.addEventListener('beforeunload',e=>{if(busy||dirty()){e.preventDefault();e.returnValue='';}});document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT|BUTTON/.test(e.target.tagName)||e.target.isContentEditable||editing||!reviewer||busy||complete)return;const u=units()[index],actions=u.kind==='unchanged'?{u:decideUnchanged}:{a:()=>decideFinding('approved'),r:()=>decideFinding('rejected'),d:()=>decideFinding('deferred'),n:()=>decideFinding('needs_research'),e:editProposal};const action=actions[e.key.toLowerCase()];if(action){e.preventDefault();action();}});
try{el('reviewer').value=localStorage.getItem('crabs-reviewer')||'';}catch(e){}el('reviewer').oninput=()=>{el('start-review').disabled=!data||!el('reviewer').value.trim();};el('start-review').onclick=startReview;el('refresh').onclick=load;load();el('preview').onclick=async()=>{try{const result=await api('/api/preview');el('patch').textContent=result.preview;el('patch').hidden=false;}catch(e){message(e.message,true);}};
