// Note-centric local review. Decisions remain finding-level and append-only.
let data, reviewer='', index=0, busy=false, editing=false, fieldDrafts={}, researchNote='', activeFindingId=null, complete=false, filter='unresolved', exportPlan=null;
const el=id=>document.getElementById(id);
const text=(tag,value,parent)=>{const x=document.createElement(tag);x.textContent=value;parent.append(x);return x;};
const button=(label,action,parent,disabled=false)=>{const b=text('button',label,parent);b.disabled=disabled;b.onclick=action;return b;};
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-CRABS-Review':'1'},body:JSON.stringify(body)}:{});const x=await r.json();if(!r.ok)throw Error(x.error||'Could not save decision');return x;}
function message(value,error=false){el('message').textContent=value;el('message').className=error?'error':'';}
function label(f){return f.review.status==='approved'?(f.review.final!==f.replacement?'Edited + approved':'Approved'):({rejected:'Rejected',deferred:'Deferred',needs_research:'Needs research',awaiting_review:'Awaiting review'}[f.review.status]);}
function comparison(oldValue,newValue){
 const old=(oldValue||'').match(/\s+|[\p{L}\p{N}_]+|[^\p{L}\p{N}_\s]/gu)||[],next=(newValue||'').match(/\s+|[\p{L}\p{N}_]+|[^\p{L}\p{N}_\s]/gu)||[],dp=Array.from({length:old.length+1},()=>Array(next.length+1).fill(0));
 for(let i=old.length-1;i>=0;i--)for(let j=next.length-1;j>=0;j--)dp[i][j]=old[i]===next[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);
 const parts=[];let i=0,j=0;const push=(tag,a,b)=>{const last=parts.at(-1);if(last&&last[0]===tag){last[1]+=a;last[2]+=b;}else parts.push([tag,a,b]);};
 while(i<old.length||j<next.length){if(i<old.length&&j<next.length&&old[i]===next[j])push('equal',old[i++],next[j++]);else if(j<next.length&&(i===old.length||dp[i][j+1]>=dp[i+1][j]))push('insert','',next[j++]);else push('delete',old[i++],'');}return parts;
}
function diff(parent,parts,side){const p=text('pre','',parent);for(const part of parts)if(part[side])text(part[0]==='equal'?'span':side===1?'del':'ins',part[side],p);}
function renderDiff(parent,original,final,labelText){const parts=comparison(original,final),wrap=text('div','',parent);wrap.className='diff-grid';const before=text('section','',wrap),after=text('section','',wrap);text('h4','Current / removed',before);diff(before,parts,1);text('h4',labelText||'Proposed / added',after);diff(after,parts,2);}
function proposalChanges(f){return f.proposed_changes||f.replacement===null?f.proposed_changes||[]:[{field:f.field,original:f.original,final:f.replacement}];}
function directProposal(f){return proposalChanges(f).length>0;}
function allNotes(){const map=new Map();for(const f of data.findings){if(!map.has(f.guid))map.set(f.guid,{guid:f.guid,note:f.note,findings:[]});map.get(f.guid).findings.push(f);}return [...map.values()];}
function noteUnresolved(n){return n.findings.some(f=>f.review.status==='awaiting_review');}
function notes(){return allNotes().filter(n=>filter==='all'||filter==='unresolved'&&noteUnresolved(n)||n.findings.some(f=>f.review.status===filter));}
function currentNote(){return notes()[index];}
function activeFinding(){const n=currentNote();return n&&n.findings.find(f=>f.id===activeFindingId);}
function baselineFields(n,f){const values=Object.fromEntries(n.note.fields.map(x=>[x.name,x.value]));if(f.review.status==='approved')for(const edit of f.review.edits||[])values[edit.field]=edit.final;return values;}
function saveVisibleDraft(){if(editing)for(const field of currentNote().note.fields){const input=el(`edit-${field.name}`);if(input)fieldDrafts[field.name]=input.value;}if(editing&&el('research-note'))researchNote=el('research-note').value;}
function changedEdits(n,f){const baseline=baselineFields(n,f);return n.note.fields.filter(x=>fieldDrafts[x.name]!==baseline[x.name]).map(x=>({field:x.name,original:x.value,final:fieldDrafts[x.name]}));}
function dirty(){if(!editing)return false;saveVisibleDraft();const n=currentNote(),f=activeFinding();return !!(n&&f&&changedEdits(n,f).length);}
function exportText(plan){const c=plan.counts;return `${c.cleared} notes cleared: ${c.unchanged} unchanged + ${c.revised} revised; ${c.added} added; ${c.deleted} deleted; ${c.conflicts} conflicts. Validation passed.\nExport ID: ${plan.id}\n\nIntended revisions:\n${JSON.stringify(plan.cleared.filter(n=>n.changes.length).map(n=>({guid:n.guid,note_id:n.note_id,changes:n.changes})),null,2)}\n\nExcluded conflicts:\n${JSON.stringify(plan.conflicts,null,2)}`;}
function canLeave(){return !busy&&(!dirty()||window.confirm('Discard unsaved edits?'));}
function clearEditor(){editing=false;fieldDrafts={};researchNote='';activeFindingId=null;}
function navigate(next){if(!canLeave())return;clearEditor();complete=false;const q=notes();index=Math.max(0,Math.min(next,q.length-1));render();}
function setFilter(value){if(!canLeave())return;clearEditor();filter=value;try{localStorage.setItem('crabs-review-filter',filter);}catch(e){}index=0;complete=false;render();}
function renderField(n,field,parent){
 const findings=n.findings.filter(f=>f.field===field.name||proposalChanges(f).some(c=>c.field===field.name)),box=text('section','',parent);box.className=findings.length?'field-with-finding':'field-context';text('h3',`${field.name}${findings.length?' · finding/proposal':' · context only'}`,box);
 if(editing){const input=text('textarea','',box);input.id=`edit-${field.name}`;input.value=fieldDrafts[field.name];input.setAttribute('aria-label',`Final value for ${field.name}`);input.disabled=busy;input.oninput=()=>{fieldDrafts[field.name]=input.value;updateSave();};renderDiff(box,field.value,fieldDrafts[field.name],'Human final / added');const proposals=findings.flatMap(proposalChanges).filter(c=>c.field===field.name);if(proposals.length)button('Use automated proposal',()=>{fieldDrafts[field.name]=proposals[0].final;render();},box,busy);button('Reset to current',()=>{fieldDrafts[field.name]=field.value;render();},box,busy);}else{text('pre',field.value,box);for(const f of findings)for(const change of proposalChanges(f))if(change.field===field.name)renderDiff(box,field.value,change.final,'Automated proposal / added');for(const f of n.findings)if(f.review.status==='approved')for(const edit of f.review.edits||[])if(edit.field===field.name)renderDiff(box,field.value,edit.final,'Approved human final / added');}
}
function updateSave(){const f=activeFinding(),n=currentNote(),save=el('save-resolution');if(save)save.disabled=busy||!changedEdits(n,f).length||(f.evidence_status==='needs_research'&&!researchNote.trim());}
function renderFinding(n,f,parent){
 const box=text('section','',parent);box.className='finding';text('h3',`${f.field} finding · ${f.severity} · ${f.category}`,box);text('p',f.review.status==='awaiting_review'?'Awaiting review':`${label(f)} · ${f.review.reviewer} · saved · ${f.review.created}`,box);text('p',f.rationale,box);if(f.researched_conclusion)text('p',`Researched conclusion: ${f.researched_conclusion}`,box);if(f.disposition)text('p',`Recommended disposition: ${f.disposition}${f.disposition!=='revise'?' (recommendation only; no field patch will be fabricated)':''}`,box);if(f.remaining_uncertainty)text('p',`Remaining uncertainty: ${f.remaining_uncertainty}`,box);text('p',`Evidence status: ${f.evidence_status} · Confidence: ${f.confidence} · Audit: ${f.audit_version} · ${f.audit_date}`,box);
 for(const e of f.evidence||[]){const p=text('p',`${e.title} — ${e.organization_authors}, ${e.publication}, ${e.year}. ${e.locator||''} `,box);const link=text('a','Source',p);link.href=e.url;link.target='_blank';link.rel='noreferrer noopener';}if(!directProposal(f)&&(!f.disposition||f.disposition==='revise'))text('p','Research was attempted but did not establish a defensible final value.',box);
 const locked=busy||!reviewer.trim()||editing,approvable=f.evidence_status!=='needs_research'&&(directProposal(f)||['retain','split','delete','replace'].includes(f.disposition));if(editing&&activeFindingId===f.id){const research=f.evidence_status==='needs_research';text('h3','Human final edit and decision',box);text('p','Saving here records an approval and exact field edits in review history. It does not apply a patch to Anki.',box);if(research){const lab=text('label','Reviewer evidence / rationale note (required for this unresolved automated finding)',box);text('p','Record what you checked and why your correction is supportable. This note is retained with the review decision but is not inserted into the card or patch.',lab);const note=text('textarea','',lab);note.id='research-note';note.value=researchNote;note.oninput=()=>{researchNote=note.value;updateSave();};}const save=button('Save human final values & Approve',()=>decideFinding(f,'approved',true),box);save.id='save-resolution';updateSave();button('Cancel edit',()=>{if(canLeave()){clearEditor();render();}},box,busy);}else if(!editing){button('Approve automated proposal (A)',()=>decideFinding(f,'approved'),box,locked||!approvable);button('Reject / keep current (R)',()=>decideFinding(f,'rejected'),box,locked);button('Defer (D)',()=>decideFinding(f,'deferred'),box,locked);button('Needs research (N)',()=>decideFinding(f,'needs_research'),box,locked);button(f.review.status==='awaiting_review'?'Edit final values + Approve (E)':'Reopen / change decision',()=>editProposal(f),box,locked);}const history=text('details','',box);text('summary','Review history and saved decision',history);text('pre',JSON.stringify(f.history,null,2),history);
}
function render(){el('queue').replaceChildren();el('session').hidden=!reviewer;el('start').hidden=!!reviewer;if(!data)return;const all=allNotes(),q=notes(),resolved=all.filter(n=>!noteUnresolved(n)).length;el('progress').textContent=`${resolved} / ${all.length} notes have no unresolved findings · ${q.length} shown · ${reviewer}`;el('status-filter').value=filter;if(!reviewer)return;if(complete||!q.length){text('h2',q.length?'Review complete':'No notes match this filter',el('queue'));if(q.length)button('Revisit notes',()=>navigate(0),el('queue'));return;}const n=q[index],a=text('article','',el('queue'));text('h2',`Note ${index+1} / ${q.length}`,a);text('p',`GUID ${n.guid} · Note ${n.note.id}`,a);text('p',`${n.findings.filter(f=>f.review.status==='awaiting_review').length} unresolved finding(s) · ${n.findings.length} total`,a);const fields=text('section','',a);fields.className='note-fields';for(const field of n.note.fields)renderField(n,field,fields);text('h2','Findings and decisions',a);for(const f of n.findings)renderFinding(n,f,a);const nav=text('nav','',a);button('Previous note',()=>navigate(index-1),nav,busy||index===0);button('Next note',()=>navigate(index+1),nav,busy||index===q.length-1);}
function editProposal(f){const n=currentNote();if(!f||!reviewer.trim()||busy||editing)return;activeFindingId=f.id;fieldDrafts=baselineFields(n,f);if(f.review.status!=='approved')for(const c of proposalChanges(f))fieldDrafts[c.field]=c.final;researchNote=f.review.comment||'';editing=true;render();el(`edit-${f.field}`).focus();}
function advanceAfterSave(guid){const q=notes();let here=q.findIndex(n=>n.guid===guid);if(here<0)here=Math.min(index,q.length-1);const next=q.findIndex((n,i)=>i>here&&noteUnresolved(n)),first=q.findIndex(noteUnresolved);if(next>=0)index=next;else if(first>=0)index=first;else if(!q.length)complete=true;else index=Math.max(0,here);}
async function decideFinding(f,status,edited=false){if(!reviewer.trim()||busy||!f||(status==='approved'&&!edited&&(f.evidence_status==='needs_research'||(!directProposal(f)&&!['retain','split','delete','replace'].includes(f.disposition)))))return;const n=currentNote();saveVisibleDraft();const edits=edited?changedEdits(n,f):status==='approved'?proposalChanges(f):undefined;if(edited&&(!edits.length||(f.evidence_status==='needs_research'&&!researchNote.trim())))return;busy=true;render();message('Saving…');try{const result=await api('/api/review',{id:f.id,status,reviewer,final:null,edits,comment:edited?researchNote:'',expected_review_id:f.review.id});if(!result.saved||!result.finding)throw Error('Save was not confirmed. Refresh before retrying.');Object.assign(f,result.finding);message(`${label(f)} · ${f.review.reviewer} · saved`);const guid=f.guid;clearEditor();advanceAfterSave(guid);}catch(e){message(e.message,true);}finally{busy=false;render();}}
async function load(){if(!canLeave())return;try{data=await api('/api/state');exportPlan=null;clearEditor();complete=false;const q=notes();index=Math.max(0,q.findIndex(noteUnresolved));el('context').textContent=`Batch: ${data.batch.version} · ${data.batch.id.slice(0,12)} · ${allNotes().length} notes · ${data.findings.length} findings · Audits: ${[...new Set(data.findings.map(f=>f.audit_version))].join(', ')}`;el('coverage').textContent=JSON.stringify({...data.coverage,notes:undefined},null,2);el('audits').textContent=JSON.stringify(data.audits,null,2);el('start-review').disabled=!el('reviewer').value.trim();if(el('export-path')&&!el('export-path').value)el('export-path').value=data.suggested_export_path||'';if(el('export-generate'))el('export-generate').disabled=true;render();}catch(e){message(e.message,true);}}
function startReview(){if(!data||!el('reviewer').value.trim())return;reviewer=el('reviewer').value.trim();try{localStorage.setItem('crabs-reviewer',reviewer);}catch(e){}index=Math.max(0,notes().findIndex(noteUnresolved));render();}
window.addEventListener('beforeunload',e=>{if(busy||dirty()){e.preventDefault();e.returnValue='';}});document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT|BUTTON/.test(e.target.tagName)||e.target.isContentEditable||editing||!reviewer||busy||complete)return;const n=currentNote(),f=n&&n.findings.find(x=>x.review.status==='awaiting_review');if(!f)return;const actions={a:()=>decideFinding(f,'approved'),r:()=>decideFinding(f,'rejected'),d:()=>decideFinding(f,'deferred'),n:()=>decideFinding(f,'needs_research'),e:()=>editProposal(f)},action=actions[e.key.toLowerCase()];if(action){e.preventDefault();action();}});
try{el('reviewer').value=localStorage.getItem('crabs-reviewer')||'';filter=localStorage.getItem('crabs-review-filter')||'unresolved';}catch(e){}el('reviewer').oninput=()=>{el('start-review').disabled=!data||!el('reviewer').value.trim();};el('status-filter').onchange=e=>setFilter(e.target.value);el('start-review').onclick=startReview;el('refresh').onclick=load;load();el('preview').onclick=async()=>{try{const result=await api('/api/preview');el('patch').textContent=result.preview;el('patch').hidden=false;}catch(e){message(e.message,true);}};
if(el('export-preview'))el('export-preview').onclick=async()=>{if(dirty()){message('Save or discard the current edits before exporting.',true);return;}try{const result=await api('/api/export-preview');exportPlan=result.plan;el('export-summary').textContent=exportText(exportPlan);el('export-summary').hidden=false;el('export-generate').disabled=!exportPlan.counts.cleared;message('Cleared-card export preview is ready. Inspect it, choose a new output path, then generate.');}catch(e){message(e.message,true);}};
if(el('export-generate'))el('export-generate').onclick=async()=>{if(!exportPlan||dirty()||busy)return;const output=el('export-path').value.trim();if(!output){message('Choose a new .apkg output path.',true);return;}busy=true;el('export-generate').disabled=true;message('Building and verifying the Anki package…');try{const result=await api('/api/export-cleared',{output,export_id:exportPlan.id});message(`Verified package created: ${result.output}`);exportPlan=null;}catch(e){message(e.message,true);el('export-generate').disabled=false;}finally{busy=false;}};
